version: 2

project_name: justdoit

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

builds:
  - id: justdoit
    main: ./cmd/justdoit
    binary: justdoit
    env:
      - CGO_ENABLED=0
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64

archives:
  - builds:
      - justdoit
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

brews:
  - name: justdoit
    directory: Formula
    homepage: "https://github.com/antoniolg/justdoit"
    description: "Time-blocking CLI for Google Tasks and Google Calendar."
    repository:
      owner: antoniolg
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    install: |
      bin.install "justdoit"
    test: |
      system "#{bin}/justdoit", "--help"
